apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-api
  namespace: saleor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saleor-api
  template:
    metadata:
      labels:
        app: saleor-api
    spec:
      containers:
      - name: saleor-api
        image: saleor/api:3.17
        env:
        - name: DATABASE_URL
          value: postgres://saleor:$(POSTGRES_PASSWORD)@postgres.saleor.svc.cluster.local:5432/saleor
        - name: REDIS_URL
          value: redis://redis.saleor.svc.cluster.local:6379/0
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: saleor-secret
              key: SECRET_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: saleor-api
  namespace: saleor
spec:
  ports:
  - port: 8000
  selector:
    app: saleor-api
